version: '3.7'

services:
  # Servicio de PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinammon-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - cinammon-network
    depends_on:
      - db

  # Servicio de base de datos (MySQL)
  db:
    image: mysql:5.7
    container_name: cinammon-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cinammon
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cinammon-network

  # Servicio de Nginx
  nginx:
    image: nginx:alpine
    container_name: cinammon-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
    networks:
      - cinammon-network
    depends_on:
      - app

networks:
  cinammon-network:
    driver: bridge

volumes:
  db_data:
