<?php

return [
    'Archivo',
    'Arial',
    'Arimo',
    'Calibri',
    'Cambria',
    'Courier New',
    'DM Sans',
    'Fira Code',
    'Franklin Gothic Medium',
    'Georgia',
    'Gill Sans',
    'Impact',
    'Inter',
    'Josefin Sans',
    'Lato',
    'Lucida Console',
    'Manrope',
    'Merriweather',
    'Montserrat',
    'Noto Sans',
    'Nunito',
    'Open Sans',
    'Orbitron',
    'Oswald',
    'PT Sans',
    'Palatino Linotype',
    'Playfair Display',
    'Poppins',
    'Quicksand',
    'Raleway',
    'Raleway Dots',
    'Roboto',
    'Rubik',
    'Segoe UI',
    'Source Sans Pro',
    'Space Grotesk',
    'Tahoma',
    'Times New Roman',
    'Titillium Web',
    'Trebuchet MS',
    'Ubuntu',
    'Verdana',
    'Work Sans',
    'Zilla Slab',
];
