return [
'Api Key' => ['view', 'view list', 'create', 'update', 'delete'],
'Database Host' => ['view', 'view list', 'create', 'update', 'delete'],
'Database' => ['view', 'view list', 'create', 'update', 'delete'],
'Egg' => ['view', 'view list', 'create', 'update', 'delete', 'import', 'export'],
'Mount' => ['view', 'view list', 'create', 'update', 'delete'],
'Node' => ['view', 'view list', 'create', 'update', 'delete'],
'Role' => ['view', 'view list', 'create', 'update', 'delete'],
'Server' => ['view', 'view list', 'create', 'update', 'delete'],
'User' => ['view', 'view list', 'create', 'update', 'delete'],
'Webhook' => ['view', 'view list', 'create', 'update', 'delete'],
'Settings' => ['view', 'update'],
'Health' => ['view'],
'Activity' => ['see tips'],
];